export const CATEGORIES = [
  "All",
  "Equipment",
  "Brand Guide",
  "Method",
  "Health",
  "Guide",
  "Beginners",
  "Performance",
  "Comparison",
  "Reading",
  "Travel",
  "Tech & Devices",
  "Clothing",
  "Studio Essentials",
  "Lagree",
  "Spinning",
] as const;
