#!/usr/bin/env python3
"""Roll the Contact and Advertise links into the footer of every page, then verify.

Re-runnable: the insert step is idempotent, so running this twice changes
nothing the second time.

This site renders its footer from one shared component
(src/components/Footer.tsx) which every page mounts, so "insert the links into
the footer of every page" resolves to two things:

  1. Footer.tsx carries both links, inserted after the existing "About" entry.
  2. Every page.tsx actually mounts that shared footer.

A page that does not mount the shared footer would not pick the links up, so
step 2 reports each such page by path rather than skipping it quietly.

  python3 scripts/rollout_footer_links.py            # insert + static checks
  python3 scripts/rollout_footer_links.py --verify   # also check built output
                                                     # (run `npm run build` first)
"""

from __future__ import annotations

import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APP = ROOT / "src" / "app"
FOOTER = ROOT / "src" / "components" / "Footer.tsx"
BUILD_APP = ROOT / ".next" / "server" / "app"
SITEMAP = BUILD_APP / "sitemap.xml.body"

NEW_LINKS = [("Contact", "/contact"), ("Advertise", "/advertise")]
ANCHOR = '  { label: "About", href: "/#about" },\n'

failures: list[str] = []
notes: list[str] = []


def fail(msg: str) -> None:
    failures.append(msg)
    print(f"  FAIL  {msg}")


def ok(msg: str) -> None:
    print(f"  ok    {msg}")


# ---------------------------------------------------------------- step 1
def insert_into_footer() -> None:
    print("[1] Footer component")
    src = FOOTER.read_text()

    missing = [(l, h) for l, h in NEW_LINKS if f'href: "{h}"' not in src]
    if not missing:
        ok(f"{FOOTER.relative_to(ROOT)} already carries Contact and Advertise")
        return

    if src.count(ANCHOR) != 1:
        fail(
            f"{FOOTER.relative_to(ROOT)}: expected exactly one 'About' anchor line, "
            f"found {src.count(ANCHOR)}. Not editing; insert by hand."
        )
        return

    block = "".join(f'  {{ label: "{l}", href: "{h}" }},\n' for l, h in missing)
    FOOTER.write_text(src.replace(ANCHOR, ANCHOR + block))
    ok(f"inserted {', '.join(l for l, _ in missing)} after the About link")


# ---------------------------------------------------------------- step 2
def check_pages_mount_footer() -> None:
    print("[2] Every page mounts the shared footer")
    pages = sorted(APP.rglob("page.tsx"))
    if not pages:
        fail("no page.tsx files found under src/app")
        return

    bad: list[str] = []
    for page in pages:
        text = page.read_text()
        mounts = "<Footer" in text
        imports = re.search(r'import\s+Footer\s+from\s+["\']@/components/Footer["\']', text)
        if not (mounts and imports):
            reason = []
            if not imports:
                reason.append("no Footer import")
            if not mounts:
                reason.append("does not render <Footer />")
            bad.append(f"{page.relative_to(ROOT)} ({', '.join(reason)})")

    if bad:
        fail(f"{len(bad)} of {len(pages)} pages do not mount the shared footer:")
        for b in bad:
            print(f"        {b}")
    else:
        ok(f"all {len(pages)} pages import and render <Footer />")


# ---------------------------------------------------------------- step 3
def check_routes_exist() -> None:
    print("[3] New routes exist and are registered in the sitemap")
    for _, href in NEW_LINKS:
        page = APP / href.strip("/") / "page.tsx"
        ok(f"{href} -> {page.relative_to(ROOT)}") if page.is_file() else fail(
            f"{href} has no page at {page.relative_to(ROOT)}"
        )

    sitemap_src = (APP / "sitemap.ts").read_text()
    for _, href in NEW_LINKS:
        if f"${{BASE_URL}}{href}`" in sitemap_src:
            ok(f"{href} listed in sitemap.ts")
        else:
            fail(f"{href} missing from sitemap.ts")


# ---------------------------------------------------------------- step 4
def collect_built_pages() -> list[Path]:
    """Prerendered site pages, excluding Next's own error boundaries.

    _not-found and _global-error are generated by the framework and have no
    page.tsx, so they carry no site footer and are not site routes.
    """
    return sorted(
        p for p in BUILD_APP.rglob("*.html") if not p.name.startswith("_")
    )


def verify_built_output() -> None:
    print("[4] Built output: footer links on every rendered page")
    if not BUILD_APP.is_dir():
        fail(f"{BUILD_APP.relative_to(ROOT)} not found. Run `npm run build` first.")
        return

    built = collect_built_pages()
    missing: list[str] = []
    for html_file in built:
        html = html_file.read_text(errors="replace")
        absent = [h for _, h in NEW_LINKS if f'href="{h}"' not in html]
        if absent:
            missing.append(f"{html_file.relative_to(BUILD_APP)} (missing {', '.join(absent)})")

    if missing:
        fail(f"{len(missing)} of {len(built)} rendered pages lack a new footer link:")
        for m in missing[:20]:
            print(f"        {m}")
    else:
        ok(f"all {len(built)} rendered pages link to /contact and /advertise")


def verify_jsonld() -> None:
    print("[5] Built output: every JSON-LD block parses")
    built = collect_built_pages()
    if not built:
        fail("no rendered pages to check")
        return

    pattern = re.compile(
        r'<script[^>]*type="application/ld\+json"[^>]*>(.*?)</script>', re.S
    )
    blocks = 0
    for html_file in built:
        html = html_file.read_text(errors="replace")
        for raw in pattern.findall(html):
            blocks += 1
            try:
                json.loads(raw)
            except json.JSONDecodeError as exc:
                fail(f"{html_file.relative_to(BUILD_APP)}: invalid JSON-LD ({exc})")

    # The two new pages must each carry the schema types they were built for.
    expected = {"contact.html": ["ContactPage", "Organization"],
                "advertise.html": ["WebPage", "BreadcrumbList"]}
    for name, types in expected.items():
        path = BUILD_APP / name
        if not path.is_file():
            fail(f"{name} was not prerendered")
            continue
        found: list[str] = []
        for raw in pattern.findall(path.read_text(errors="replace")):
            try:
                data = json.loads(raw)
            except json.JSONDecodeError:
                continue
            found += [n.get("@type") for n in data.get("@graph", []) if isinstance(n, dict)]
        absent = [t for t in types if t not in found]
        if absent:
            fail(f"{name}: JSON-LD missing {', '.join(absent)} (found {found})")
        else:
            ok(f"{name}: {' + '.join(types)} present")

    if not failures:
        ok(f"{blocks} JSON-LD blocks parsed across {len(built)} pages")


def verify_sitemap() -> None:
    print("[6] Built sitemap is valid XML and contains the new URLs")
    if not SITEMAP.is_file():
        fail(f"{SITEMAP.relative_to(ROOT)} not found. Run `npm run build` first.")
        return
    try:
        root = ET.fromstring(SITEMAP.read_text())
    except ET.ParseError as exc:
        fail(f"sitemap is not valid XML: {exc}")
        return

    ns = "{http://www.sitemaps.org/schemas/sitemap/0.9}"
    urls = [loc.text for loc in root.iter(f"{ns}loc")]
    ok(f"valid XML, {len(urls)} URLs")

    for _, href in NEW_LINKS:
        target = f"https://pilatescollectiveclub.com{href}"
        ok(f"{target} in sitemap") if target in urls else fail(f"{target} absent from sitemap")

    if len(urls) != len(set(urls)):
        dupes = {u for u in urls if urls.count(u) > 1}
        fail(f"duplicate sitemap URLs: {sorted(dupes)}")


def verify_internal_links() -> None:
    print("[7] Internal links resolve to real routes")
    routes = {"/"} | {
        "/" + str(p.parent.relative_to(APP)).replace("\\", "/")
        for p in APP.rglob("page.tsx")
        if p.parent != APP
    }

    # Anchors and query strings hang off a route; strip them before matching.
    bad: dict[str, set[str]] = {}
    for page in sorted(APP.rglob("page.tsx")):
        for href in re.findall(r'href=["\'](/[^"\'#?]*)', page.read_text()):
            clean = href.rstrip("/") or "/"
            if clean in routes or clean.startswith(("/pictures/", "/icon", "/apple-icon")):
                continue
            bad.setdefault(str(page.relative_to(ROOT)), set()).add(href)

    if bad:
        total = sum(len(v) for v in bad.values())
        fail(f"{total} internal links point at routes that do not exist:")
        for page, hrefs in list(bad.items())[:20]:
            print(f"        {page}: {', '.join(sorted(hrefs))}")
    else:
        ok(f"every internal href matches one of {len(routes)} routes")


def main() -> int:
    verify = "--verify" in sys.argv

    insert_into_footer()
    check_pages_mount_footer()
    check_routes_exist()
    verify_internal_links()

    if verify:
        verify_built_output()
        verify_jsonld()
        verify_sitemap()
    else:
        notes.append("Static checks only. Re-run with --verify after `npm run build` "
                     "to check the rendered output, JSON-LD and sitemap.")

    print()
    for n in notes:
        print(f"note: {n}")
    if failures:
        print(f"RESULT: {len(failures)} check(s) failed.")
        return 1
    print("RESULT: all checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
