import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BlogFilter, { CATEGORIES } from "@/components/BlogFilter";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pilates Journal — Equipment Reviews, Method Guides & Studio Advice",
  description: "In-depth Pilates guides: equipment reviews, beginner advice, method comparisons, studio tips, and brand guides. Everything a serious practitioner needs to know.",
  keywords: ["pilates blog", "pilates equipment reviews", "pilates for beginners", "reformer pilates guide", "pilates vs yoga", "classical pilates", "best pilates mat", "pilates advice", "pilates method", "pilates tips 2026", "pilates articles"],
  openGraph: {
    title: "Pilates Journal — Equipment Reviews, Method Guides & Studio Advice",
    description: "In-depth Pilates guides covering equipment reviews, beginner advice, method comparisons, and studio tips.",
    type: "website",
    url: "https://pilatescollectiveclub.com/blog",
    images: [{ url: "https://pilatescollectiveclub.com/pictures/roxana-popovici-aY5uOJ2o96g-unsplash.jpg", width: 1200, height: 630, alt: "Pilates Collective Club Journal" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Pilates Journal — Equipment Reviews, Method Guides & Studio Advice",
    description: "In-depth Pilates guides covering equipment reviews, beginner advice, method comparisons, and studio tips.",
    images: ["https://pilatescollectiveclub.com/pictures/roxana-popovici-aY5uOJ2o96g-unsplash.jpg"],
  },
  alternates: {
    canonical: "https://pilatescollectiveclub.com/blog",
  },
  robots: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
};

const posts = [
  {
    title: "Best Premium Pilates Reformers (2026): $2,000–$5,000+ Reviewed",
    excerpt: "Balanced Body Allegro 2, Merrithew V2 Max, Gratz, Elina Elite Wood, Peak MVe — verified prices and honest assessments for serious home practitioners.",
    href: "/blog/best-premium-pilates-reformer",
    category: "Equipment",
    readTime: "14 min",
    imageUrl: "/pictures/roxana-popovici-aY5uOJ2o96g-unsplash.jpg",
  },
  {
    title: "Merrithew V2 Max Review (2026): Worth the Upgrade?",
    excerpt: "Patented retractable ropes, 24-inch carriage, high-precision springs — a detailed assessment of Merrithew's most advanced reformer vs the SPX Max.",
    href: "/blog/merrithew-v2-max-review",
    category: "Equipment",
    readTime: "11 min",
    imageUrl: "/pictures/samantha-sheppard-b8Q5fHBsyik-unsplash.jpg",
  },
  {
    title: "Best Sports Bras for Pilates (2026): Coverage & Studio Style",
    excerpt: "The bra your instructor is wearing — and the four alternatives worth considering across every price point.",
    href: "/blog/best-pilates-sports-bra",
    category: "Equipment",
    readTime: "8 min",
    imageUrl: "/pictures/jessica-streser-5ai6kpW4NOw-unsplash.jpg",
  },
  {
    title: "Best Pilates Shorts (2026): Biker Shorts & Beyond",
    excerpt: "Instructors need to see your knee and hip alignment. Here's what the best-dressed reformer regulars are wearing.",
    href: "/blog/best-pilates-shorts",
    category: "Equipment",
    readTime: "7 min",
    imageUrl: "/pictures/roxana-popovici-lKe5jm-Sypw-unsplash.jpg",
  },
  {
    title: "Best Pilates Ankle Weights (2026): Bala Bangles & Alternatives",
    excerpt: "The accessory that defines the boutique Pilates aesthetic — and the four alternatives that also deliver.",
    href: "/blog/best-pilates-ankle-weights",
    category: "Equipment",
    readTime: "7 min",
    imageUrl: "/pictures/jade-stephens-N21356amsyw-unsplash.jpg",
  },
  {
    title: "Best Mini Pilates Reformer (2026): Compact Machines Reviewed",
    excerpt: "Full reformer experience in a smaller footprint — the compact machines that genuinely work.",
    href: "/blog/best-mini-pilates-reformer",
    category: "Equipment",
    readTime: "9 min",
    imageUrl: "/pictures/elena-kloppenburg-erUC4fTtCuo-unsplash.jpg",
  },
  {
    title: "Best Pilates Reformer Under $1,000 (2026)",
    excerpt: "The honest guide to every reformer under four figures — spring vs cord, what you sacrifice, and our pick.",
    href: "/blog/best-pilates-reformer-under-1000",
    category: "Equipment",
    readTime: "8 min",
    imageUrl: "/pictures/roxana-popovici-aY5uOJ2o96g-unsplash.jpg",
  },
  {
    title: "Best Online Pilates Classes (2026): Platforms Compared",
    excerpt: "Pilates Anytime, Alo Moves, and more — the platforms worth a subscription for home and travel practice.",
    href: "/blog/best-online-pilates-classes",
    category: "Brand Guide",
    readTime: "9 min",
    imageUrl: "/pictures/ginny-rose-stewart-UxkcSzRWM2s-unsplash.jpg",
  },
  {
    title: "Pilates for Weight Loss: What the Evidence Says",
    excerpt: "Does Pilates actually help you lose weight? An honest evidence-based answer with realistic expectations.",
    href: "/blog/pilates-for-weight-loss",
    category: "Health",
    readTime: "10 min",
    imageUrl: "/pictures/ahmet-kurt-0fiVrPJg5kU-unsplash.jpg",
  },
  {
    title: "10 Pilates Exercises for Beginners: The Essential Foundation",
    excerpt: "The Hundred, Roll Up, Single Leg Stretch — the 10 exercises every beginner should master before anything else.",
    href: "/blog/pilates-exercises-for-beginners",
    category: "Beginners",
    readTime: "11 min",
    imageUrl: "/pictures/ginny-rose-stewart-UxkcSzRWM2s-unsplash.jpg",
  },
  {
    title: "Pilates for Seniors: Safe, Effective & Evidence-Based",
    excerpt: "Why Pilates is one of the best exercises for over-60s — fall prevention, bone density, and balance, covered.",
    href: "/blog/pilates-for-seniors",
    category: "Health",
    readTime: "10 min",
    imageUrl: "/pictures/mathilde-langevin-aBJ3A-2LJyU-unsplash.jpg",
  },
  {
    title: "How Often Should You Do Pilates? The Evidence-Based Answer",
    excerpt: "Beginner or advanced, daily or twice weekly — exactly how much Pilates you need for your specific goals.",
    href: "/blog/how-often-should-you-do-pilates",
    category: "Guide",
    readTime: "7 min",
    imageUrl: "/pictures/roxana-popovici-2QeonB1SdQk-unsplash.jpg",
  },
  {
    title: "Pilates for Better Posture: The Exercises That Work",
    excerpt: "Forward head, rounded shoulders, anterior pelvic tilt — the Pilates exercises that specifically correct each pattern.",
    href: "/blog/pilates-for-posture",
    category: "Health",
    readTime: "9 min",
    imageUrl: "/pictures/junseong-lee-AX8cf6mkCzw-unsplash.jpg",
  },
  {
    title: "Pilates vs Gym: An Honest Comparison",
    excerpt: "Strength, cost, body composition, injury risk — an evidence-based assessment of both, and who should choose what.",
    href: "/blog/pilates-vs-gym",
    category: "Method",
    readTime: "10 min",
    imageUrl: "/pictures/ahmet-kurt-0xn-8kRWOhE-unsplash.jpg",
  },
  {
    title: "Pilates and the Pelvic Floor: What Actually Works",
    excerpt: "The evidence on Pilates for pelvic floor health — which exercises help, which to avoid, and postpartum considerations.",
    href: "/blog/pilates-for-pelvic-floor",
    category: "Health",
    readTime: "10 min",
    imageUrl: "/pictures/juls-p-lB6lbkbe1XA-unsplash.jpg",
  },
  {
    title: "Is Reformer Pilates Worth It? An Honest Assessment",
    excerpt: "The real cost of reformer Pilates, what you actually get, and whether a home reformer makes financial sense.",
    href: "/blog/is-reformer-pilates-worth-it",
    category: "Guide",
    readTime: "9 min",
    imageUrl: "/pictures/esma-eserghep-NUQi80iMLrI-unsplash.jpg",
  },
  {
    title: "Pilates for a Flat Stomach: What Works and What Doesn't",
    excerpt: "The honest truth about Pilates and the abdomen — and the exercises that actually change your core shape.",
    href: "/blog/pilates-for-flat-stomach",
    category: "Health",
    readTime: "8 min",
    imageUrl: "/pictures/roxana-popovici-Zp4APUiwEsM-unsplash.jpg",
  },
  {
    title: "Best Home Pilates Reformer (2026): Every Budget",
    excerpt: "A quality home reformer changes your practice permanently. We tested every price tier so you know exactly what you get.",
    href: "/blog/best-home-pilates-reformer",
    category: "Equipment",
    readTime: "11 min",
    imageUrl: "/pictures/roxana-popovici-aY5uOJ2o96g-unsplash.jpg",
    featured: true,
  },
  {
    title: "Best Pilates Grip Socks (2026): Tested & Ranked",
    excerpt: "Required at virtually every reformer studio. Five options across every price point and preference.",
    href: "/blog/best-pilates-grip-socks",
    category: "Equipment",
    readTime: "7 min",
    imageUrl: "/pictures/jade-stephens-N21356amsyw-unsplash.jpg",
  },
  {
    title: "Best Pilates Books (2026): Every Level",
    excerpt: "From Joseph Pilates' 1945 manifesto to modern biomechanics texts. The books we recommend most frequently.",
    href: "/blog/best-pilates-books",
    category: "Reading",
    readTime: "8 min",
    imageUrl: "/pictures/mathilde-langevin-aBJ3A-2LJyU-unsplash.jpg",
  },
  {
    title: "Best Pilates Ball (2026): Mini & Stability",
    excerpt: "Mini ball or stability ball? We explain the difference and cover the best of both.",
    href: "/blog/best-pilates-ball",
    category: "Equipment",
    readTime: "8 min",
    imageUrl: "/pictures/dane-wetton-AkSJQnem75Y-unsplash.jpg",
  },
  {
    title: "What to Wear to Pilates (2026)",
    excerpt: "Instructors need to see your alignment. Here's exactly what works — and what to avoid — for reformer, mat, and barre.",
    href: "/blog/what-to-wear-to-pilates",
    category: "Beginners",
    readTime: "6 min",
    imageUrl: "/pictures/jessica-streser-5ai6kpW4NOw-unsplash.jpg",
  },
  {
    title: "Best Pilates Equipment for Home Practice",
    excerpt: "The essential kit for a serious home setup, from mats to resistance rings to foam rollers.",
    href: "/blog/best-pilates-equipment-for-home-practice",
    category: "Equipment",
    readTime: "10 min",
    imageUrl: "/pictures/elena-kloppenburg-erUC4fTtCuo-unsplash.jpg",
  },
  {
    title: "Beginner's Guide to Reformer Pilates",
    excerpt: "What to expect from your first reformer class and how to prepare.",
    href: "/blog/beginners-guide-to-reformer-pilates",
    category: "Beginners",
    readTime: "8 min",
    imageUrl: "/pictures/esma-eserghep-NUQi80iMLrI-unsplash.jpg",
  },
  {
    title: "6 Core Principles of Pilates Explained",
    excerpt: "Breath, concentration, control, centring, precision, flow — understanding the method's foundations.",
    href: "/blog/6-core-principles-of-pilates-explained",
    category: "Method",
    readTime: "7 min",
    imageUrl: "/pictures/ginny-rose-stewart-UxkcSzRWM2s-unsplash.jpg",
  },
  {
    title: "Pilates vs Yoga: Which Is Right for You?",
    excerpt: "An honest comparison of two movement disciplines that are often confused but serve different goals.",
    href: "/blog/pilates-vs-yoga",
    category: "Method",
    readTime: "9 min",
    imageUrl: "/pictures/henrique-ferreira-omiTbS-nb_M-unsplash.jpg",
  },
  {
    title: "Pilates for Back Pain: What the Evidence Says",
    excerpt: "Clinical research meets practical guidance on using Pilates to address chronic lower back pain.",
    href: "/blog/pilates-for-back-pain",
    category: "Health",
    readTime: "10 min",
    imageUrl: "/pictures/junseong-lee-AX8cf6mkCzw-unsplash.jpg",
  },
  {
    title: "Pilates for Athletes",
    excerpt: "How professional athletes use Pilates for injury prevention and performance enhancement.",
    href: "/blog/pilates-for-athletes",
    category: "Performance",
    readTime: "9 min",
    imageUrl: "/pictures/ahmet-kurt-0fiVrPJg5kU-unsplash.jpg",
  },
  {
    title: "Pilates and Pregnancy",
    excerpt: "Safe, effective Pilates throughout pregnancy — trimester by trimester.",
    href: "/blog/pilates-and-pregnancy",
    category: "Health",
    readTime: "11 min",
    imageUrl: "/pictures/juls-p-lB6lbkbe1XA-unsplash.jpg",
  },
  {
    title: "Classical vs Contemporary Pilates",
    excerpt: "The split between the original Contrology method and modern functional interpretations.",
    href: "/blog/classical-vs-contemporary-pilates",
    category: "Method",
    readTime: "8 min",
    imageUrl: "/pictures/junseong-lee-G9H5edUL0T8-unsplash.jpg",
  },
  {
    title: "How to Choose a Pilates Instructor",
    excerpt: "Credentials, lineage, teaching style — what actually matters when selecting your teacher.",
    href: "/blog/how-to-choose-a-pilates-instructor",
    category: "Guide",
    readTime: "7 min",
    imageUrl: "/pictures/roxana-popovici-hiHBILFNah4-unsplash.jpg",
  },
  {
    title: "How to Build a Consistent Pilates Practice",
    excerpt: "The habits and routines that separate practitioners who see results from those who plateau.",
    href: "/blog/how-to-build-a-consistent-pilates-practice",
    category: "Guide",
    readTime: "8 min",
    imageUrl: "/pictures/logan-weaver-lgnwvr-u76Gd0hP5w4-unsplash.jpg",
  },
  {
    title: "Best Pilates Retreats in Europe (2026)",
    excerpt: "Immersive studio retreats across Switzerland, France, Italy, and Portugal for serious practitioners.",
    href: "/blog/best-pilates-retreats-europe",
    category: "Travel",
    readTime: "12 min",
    imageUrl: "/pictures/tomi-blasic-tj0sM4gHlns-unsplash.jpg",
  },
  {
    title: "Best Pilates Leggings (2026): Tested & Ranked",
    excerpt: "From Lululemon Align to CRZ YOGA — the leggings that genuinely serve the method, tested for opacity, waistband stability, and reformer performance.",
    href: "/blog/best-pilates-leggings",
    category: "Equipment",
    readTime: "9 min",
    imageUrl: "/pictures/roxana-popovici-lKe5jm-Sypw-unsplash.jpg",
  },
  {
    title: "Pilates Reformer vs Mat: Key Differences Explained",
    excerpt: "What's actually different between reformer and mat Pilates — which is harder, what you get from each, and how serious practitioners approach both.",
    href: "/blog/pilates-reformer-vs-mat",
    category: "Method",
    readTime: "10 min",
    imageUrl: "/pictures/ahmet-kurt-0xn-8kRWOhE-unsplash.jpg",
  },
  {
    title: "Best Pilates Resistance Bands (2026)",
    excerpt: "Long bands, loop bands, and fabric options — the resistance bands that actually perform in a serious Pilates context.",
    href: "/blog/best-pilates-resistance-bands",
    category: "Equipment",
    readTime: "8 min",
    imageUrl: "/pictures/ahmet-kurt-a1IhqqW8JQE-unsplash.jpg",
  },
  {
    title: "Best Pilates Starter Kit (2026): What to Buy First",
    excerpt: "Mat, grip socks, resistance bands, Pilates ring — exactly what to buy, in what order, when starting your Pilates practice.",
    href: "/blog/best-pilates-starter-kit",
    category: "Beginners",
    readTime: "9 min",
    imageUrl: "/pictures/roxana-popovici-Zp4APUiwEsM-unsplash.jpg",
  },
  {
    title: "Best Pilates Reformer Accessories (2026)",
    excerpt: "Sticky pads, jump boards, long box, leather straps — the five accessories that most meaningfully upgrade your reformer practice.",
    href: "/blog/best-pilates-reformer-accessories",
    category: "Equipment",
    readTime: "9 min",
    imageUrl: "/pictures/samantha-sheppard-b8Q5fHBsyik-unsplash.jpg",
  },
  {
    title: "Best Pilates Mat (2026): Firmness, Grip & Durability Tested",
    excerpt: "The Pilates mat is your most important equipment purchase. We tested five across firmness, grip, and spinal feedback — from Manduka PRO to travel options.",
    href: "/blog/best-pilates-mat",
    category: "Equipment",
    readTime: "9 min",
    imageUrl: "/pictures/dane-wetton-t1NEMSm1rgI-unsplash.jpg",
  },
  {
    title: "Best Foam Roller for Pilates (2026)",
    excerpt: "Spinal mobilisation, myofascial release, balance challenge — the foam rollers that actually perform in a serious Pilates context.",
    href: "/blog/best-pilates-foam-roller",
    category: "Equipment",
    readTime: "8 min",
    imageUrl: "/pictures/roxana-popovici-2QeonB1SdQk-unsplash.jpg",
  },
  {
    title: "Best Pilates Ring / Magic Circle (2026)",
    excerpt: "Joseph Pilates invented it. We tested five versions — from STOTT to Balanced Body — for resistance, pad quality, and durability.",
    href: "/blog/best-pilates-ring",
    category: "Equipment",
    readTime: "8 min",
    imageUrl: "/pictures/roxana-popovici-5JQxj-zc5ng-unsplash.jpg",
  },
  {
    title: "Best Pilates Reformer Brands (2026): Compared Honestly",
    excerpt: "Gratz vs Balanced Body vs Merrithew vs Align-Pilates — an honest brand comparison for home users, studio owners, and serious practitioners.",
    href: "/blog/best-pilates-reformer-brands",
    category: "Equipment",
    readTime: "12 min",
    imageUrl: "/pictures/roxana-popovici-cZ0WYsBFHhs-unsplash.jpg",
  },
  {
    title: "Best Pilates Tops & Sports Bras (2026)",
    excerpt: "Tested for coverage across positions, instructor visibility, and reformer comfort. Lululemon, Alo, Varley, and more ranked honestly.",
    href: "/blog/best-pilates-workout-tops",
    category: "Equipment",
    readTime: "8 min",
    imageUrl: "/pictures/jessica-streser-5ai6kpW4NOw-unsplash.jpg",
  },
  {
    title: "Pilates for Runners: The Work That Actually Helps",
    excerpt: "How Pilates addresses glute medius weakness, hip flexor tightness, thoracic stiffness, and breathing economy — the specific deficits that cause running injuries.",
    href: "/blog/pilates-for-runners",
    category: "Performance",
    readTime: "11 min",
    imageUrl: "/pictures/ahmet-kurt-0fiVrPJg5kU-unsplash.jpg",
  },
  {
    title: "Pilates for Scoliosis: What Actually Works",
    excerpt: "An honest guide — what the research shows, which exercises help your specific curve pattern, what to avoid, and how to find an instructor who understands spinal asymmetry.",
    href: "/blog/pilates-for-scoliosis",
    category: "Health",
    readTime: "12 min",
    imageUrl: "/pictures/junseong-lee-AX8cf6mkCzw-unsplash.jpg",
  },
  {
    title: "Pilates During Menopause: Bone Density, Hormones & Practice",
    excerpt: "How oestrogen decline changes the musculoskeletal system, why Pilates is exceptionally well-positioned to help, and how to adapt your practice.",
    href: "/blog/pilates-for-menopause",
    category: "Health",
    readTime: "13 min",
    imageUrl: "/pictures/ginny-rose-stewart-UxkcSzRWM2s-unsplash.jpg",
  },
  {
    title: "The History of Pilates: From Joseph Pilates to Today",
    excerpt: "From internment camps to the New York City Ballet building to global boutique studios — the complete, honest history of how the method developed and fractured.",
    href: "/blog/pilates-history",
    category: "Method",
    readTime: "14 min",
    imageUrl: "/pictures/mathilde-langevin-aBJ3A-2LJyU-unsplash.jpg",
  },
  {
    title: "How to Find a Great Pilates Studio (Before You Commit)",
    excerpt: "The specific green flags, red flags, and questions that separate excellent studios from mediocre ones — before you spend on a class pack.",
    href: "/blog/how-to-find-a-good-pilates-studio",
    category: "Guide",
    readTime: "10 min",
    imageUrl: "/pictures/samantha-sheppard-b8Q5fHBsyik-unsplash.jpg",
  },
  {
    title: "Alo Yoga for Pilates (2026): Best Pieces & Honest Review",
    excerpt: "The Airbrush legging, Airlift bra, Alo Moves app — what works for Pilates, what doesn't, and an honest assessment of the brand that defines the boutique studio aesthetic.",
    href: "/blog/alo-yoga-pilates",
    category: "Brand Guide",
    readTime: "10 min",
    imageUrl: "/pictures/roxana-popovici-lKe5jm-Sypw-unsplash.jpg",
  },
  {
    title: "Lululemon for Pilates (2026): Best Pieces for Studio & Reformer",
    excerpt: "The Align legging, Align bra, Flow Y, Define jacket — the Lululemon pieces that genuinely serve the method, and the ones to skip.",
    href: "/blog/lululemon-pilates",
    category: "Brand Guide",
    readTime: "10 min",
    imageUrl: "/pictures/jessica-streser-5ai6kpW4NOw-unsplash.jpg",
  },
  {
    title: "Club Pilates Review (2026): Is It Worth It?",
    excerpt: "An honest assessment of the world's largest Pilates franchise — equipment, instructor training, class sizes, membership pricing, and who should look elsewhere.",
    href: "/blog/club-pilates-review",
    category: "Brand Guide",
    readTime: "11 min",
    imageUrl: "/pictures/esma-eserghep-NUQi80iMLrI-unsplash.jpg",
  },
  {
    title: "Balanced Body vs Merrithew: Which Reformer Is Right for You?",
    excerpt: "The most detailed head-to-head of the two dominant professional reformer brands — spring feel, accessories, price, training alignment, and the verdict by use case.",
    href: "/blog/balanced-body-vs-merrithew",
    category: "Brand Guide",
    readTime: "13 min",
    imageUrl: "/pictures/roxana-popovici-aY5uOJ2o96g-unsplash.jpg",
  },
  {
    title: "Varley for Pilates (2026): The Boutique Studio Brand Reviewed",
    excerpt: "The Reeves legging, Stratford bra, and Paloma tank — the Varley pieces built for the boutique reformer studio, honestly reviewed.",
    href: "/blog/varley-pilates-activewear",
    category: "Brand Guide",
    readTime: "9 min",
    imageUrl: "/pictures/logan-weaver-lgnwvr-u76Gd0hP5w4-unsplash.jpg",
  },
  {
    title: "Gymshark for Pilates (2026): Best Pieces & Honest Review",
    excerpt: "Gymshark has pivoted hard toward the Pilates market. The Flex legging and Vital Seamless set honestly reviewed for studio and reformer use.",
    href: "/blog/gymshark-pilates",
    category: "Brand Guide",
    readTime: "8 min",
    imageUrl: "/pictures/ahmet-kurt-0xn-8kRWOhE-unsplash.jpg",
  },
  {
    title: "Sweaty Betty for Pilates (2026): Best Pieces & Honest Review",
    excerpt: "The original UK boutique fitness brand. Power Workout Legging, Garudasana, and more — honest review for Pilates practitioners in London and beyond.",
    href: "/blog/sweaty-betty-pilates",
    category: "Brand Guide",
    readTime: "9 min",
    imageUrl: "/pictures/jade-stephens-N21356amsyw-unsplash.jpg",
  },
  {
    title: "Splits59 for Pilates (2026): The Brand Built for the Method",
    excerpt: "Splits59 was designed explicitly for Pilates and barre. The Raquel legging is the method's finest piece of activewear — here is why.",
    href: "/blog/splits59-pilates",
    category: "Brand Guide",
    readTime: "9 min",
    imageUrl: "/pictures/elena-kloppenburg-erUC4fTtCuo-unsplash.jpg",
  },
  {
    title: "Athleta for Pilates (2026): Best Pieces & Honest Review",
    excerpt: "Gap's B Corp-certified activewear brand offers premium quality at a meaningful discount to Lululemon. The Salutation Stash Tight reviewed for studio use.",
    href: "/blog/athleta-pilates",
    category: "Brand Guide",
    readTime: "8 min",
    imageUrl: "/pictures/ginny-rose-stewart-UxkcSzRWM2s-unsplash.jpg",
  },
  {
    title: "Manduka Pilates Mat (2026): PRO, eKO & PRO Lite Compared",
    excerpt: "The gold standard in Pilates mats. PRO vs eKO vs PRO Lite — which Manduka is right for your practice, home studio, or travel needs.",
    href: "/blog/manduka-pilates-mat",
    category: "Equipment",
    readTime: "9 min",
    imageUrl: "/pictures/dane-wetton-t1NEMSm1rgI-unsplash.jpg",
  },
  {
    title: "Vuori for Pilates (2026): Best Pieces for Men & Women",
    excerpt: "The only major brand with genuinely great Pilates-appropriate pieces for men. Women's range excellent too — Performance Jogger and Daily Legging reviewed.",
    href: "/blog/vuori-pilates",
    category: "Brand Guide",
    readTime: "8 min",
    imageUrl: "/pictures/ahmet-kurt-0fiVrPJg5kU-unsplash.jpg",
  },
  {
    title: "Free People Movement for Pilates (2026): Best Pieces & Review",
    excerpt: "The pilates girl aesthetic brand. Good Karma Legging, Barely There Bra, Roll With It Hoodie — lifestyle-forward activewear honestly reviewed for studio performance.",
    href: "/blog/free-people-movement-pilates",
    category: "Brand Guide",
    readTime: "8 min",
    imageUrl: "/pictures/roxana-popovici-hiHBILFNah4-unsplash.jpg",
  },
  {
    title: "Girlfriend Collective for Pilates (2026): Sustainable Activewear Reviewed",
    excerpt: "Made from recycled water bottles and fishing nets. Compressive Legging, Float Bra, and Bike Short — the ethical brand that genuinely performs, honestly reviewed.",
    href: "/blog/girlfriend-collective-pilates",
    category: "Brand Guide",
    readTime: "8 min",
    imageUrl: "/pictures/juls-p-lB6lbkbe1XA-unsplash.jpg",
  },
  {
    title: "Lululemon Align vs Alo Airbrush Leggings (2026): The Honest Verdict",
    excerpt: "The two most-discussed Pilates leggings go head-to-head — fabric feel, compression, opacity, reformer performance, and which one is actually worth your money.",
    href: "/blog/lululemon-align-vs-alo-airbrush",
    category: "Comparison",
    readTime: "10 min",
    imageUrl: "/pictures/roxana-popovici-lKe5jm-Sypw-unsplash.jpg",
  },
  {
    title: "Pilates vs Barre (2026): Which Workout Is Right for You?",
    excerpt: "Both are low-impact, studio-based, and devoted to precision. Here's how they actually differ — and which one suits your goals, fitness level, and lifestyle.",
    href: "/blog/pilates-vs-barre",
    category: "Guide",
    readTime: "8 min",
    imageUrl: "/pictures/roxana-popovici-5JQxj-zc5ng-unsplash.jpg",
  },
];

const blogJsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "CollectionPage",
      "@id": "https://pilatescollectiveclub.com/blog/#webpage",
      "url": "https://pilatescollectiveclub.com/blog",
      "name": "Pilates Journal — Equipment Reviews, Method Guides & Studio Advice",
      "description": "In-depth Pilates guides covering equipment reviews, beginner advice, method comparisons, and studio tips.",
      "isPartOf": { "@id": "https://pilatescollectiveclub.com/#website" },
      "inLanguage": "en-US",
    },
    {
      "@type": "ItemList",
      "name": "Pilates Articles and Equipment Reviews",
      "url": "https://pilatescollectiveclub.com/blog",
      "numberOfItems": posts.length,
      "itemListElement": posts.map((p, i) => ({
        "@type": "ListItem",
        "position": i + 1,
        "url": `https://pilatescollectiveclub.com${p.href}`,
        "name": p.title,
      })),
    },
  ],
};

export default async function BlogPage({ searchParams }: { searchParams: Promise<{ category?: string }> }) {
  const { category } = await searchParams;
  const initialCategory = CATEGORIES.find((c) => c.toLowerCase() === (category ?? "").toLowerCase()) ?? "All";
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(blogJsonLd) }} />
      <Header />
      <main className="pt-20" style={{ backgroundColor: "#fcf9f8", minHeight: "100vh" }}>

        {/* Hero */}
        <section className="px-6 pt-16 pb-12">
          <div className="max-w-5xl mx-auto">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] mb-4" style={{ color: "#8b4a31", fontFamily: "'Montserrat', sans-serif" }}>Journal</p>
            <h1 className="text-5xl md:text-6xl font-semibold leading-tight mb-4" style={{ color: "#1b1c1c", fontFamily: "'Playfair Display', serif" }}>
              The Blog
            </h1>
            <p className="text-lg max-w-xl" style={{ color: "#53433e", fontFamily: "'Montserrat', sans-serif", fontWeight: 300 }}>
              Guides, equipment reviews, and studio advice for every stage of your practice.
            </p>
          </div>
        </section>

        <BlogFilter posts={posts} initialCategory={initialCategory} />

      </main>
      <Footer />
    </>
  );
}
